name: CI

on: [push]

jobs:

  python-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Get changes python files
      id: files
      run: |
        echo "::set-output name=all::$(echo $(git ls-tree --full-tree -r --name-only HEAD | grep \.py$))"
        echo "::set-output name=changed::$(echo $(git diff --name-only ${{ github.sha }} | grep \.py$))"

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
      if: steps.files.outputs.all

    - name: Install dependencies
      run: |
        python -m pip install ".[dev]"
      if: steps.files.outputs.all

    - name: Analyse the code with black
      run: black . --check --verbose --diff --color
      if: steps.files.outputs.all

    - name: Analyse the documentation with pydocstyle
      run: pydocstyle timeti
      if: steps.files.outputs.all

    - name: Analyse types with mypy
      run: mypy timeti
      if: steps.files.outputs.all

    - name: Analyse imports with isort
      run: isort . --check --diff --color
      if: steps.files.outputs.all


  test:
    runs-on: ubuntu-latest
    needs: [python-lint]

    steps:
    - name: Clone repo
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install .

    - name: Run doctests
      run: python -m doctest -v timeti/clockface.py 

    - name: Run tests
      run: python -m unittest discover -v -s tests 

    - name: Run examples
      run: for f in examples/*.py; do echo "\n$f" && python "$f"; done
