name: ci/cd

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Get modified python files
      id: files
      run: echo "::set-output name=modified::$(echo $(git diff --name-only ${{ github.sha }} | grep \.py$))"

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: Install dependencies
      run: python -m pip install ".[dev]"

    - name: Analyse the code with black
      run: black . --check --verbose --diff --color
      if: steps.files.outputs.modified

    - name: Analyse the documentation with pydocstyle
      run: pydocstyle timeti
      if: steps.files.outputs.modified

    - name: Analyse types with mypy
      run: mypy timeti
      if: steps.files.outputs.modified

    - name: Analyse imports with isort
      run: isort . --check --diff --color
      if: steps.files.outputs.modified

    - name: Run doctests
      run: python -m doctest -v timeti/clockface.py 

    - name: Run tests
      run: python -m unittest discover -v -s tests 

    - name: Run examples
      run: for f in examples/*.py; do echo "\n$f" && python "$f"; done
